### ISSUE TITLE
Can't addSubview or insertSubview to the JellyView

### ISSUE THREAD

**Issue by KittenYang** [victorBaro/VBFJellyView#3]
Because the JellyView achieve jelly bounce effect by following the tracks of the subviews,so if I addSubview or insertSubview to the JellyView,it will be weird. Do you guys have any solutions?

**Comment by victorBaro** [comment]
You can't add a subview because what you see on the screen is a CAShapeLayer. You can add a sublayer to it if you want to.
I am planning to update the class to have 1 view (the middle view) public, so you will be able to add a subview to it if you want to.
In the meantime, do it yourself, set the middle view as public so con can access to it to add a subview. I hope that helps.

**Comment by KittenYang** [comment]
Yes，I redesigned the code so now i can add the subview.

**Comment by victorBaro** [comment]
Can you PR?

Victor Baro

**Comment by KittenYang** [comment]
Oops,I just recreated a project and some principles are different from you.
